pqclean_hqc: Fix build on GCC-12
Make index variable `i` immediate by unrolling the loop. This is just lucky
guess that's worked, because similar in function intrinsic
`_mm256_extract_epi16` requires immediate value for its index.

Workaround to the (perhaps) GCC 12 bug:

  In function 'find_peaks',
      inlined from 'PQCLEAN_HQCRMRS192_AVX2_reed_muller_decode' at /usr/src/RPM/BUILD/liboqs-0.7.1/src/kem/hqc/pqclean_hqc-rmrs-192_avx2/reed_muller.c:387:18:
  /usr/src/RPM/BUILD/liboqs-0.7.1/src/kem/hqc/pqclean_hqc-rmrs-192_avx2/reed_muller.c:336:44: error: 'tmp' is used uninitialized [-Werror=uninitialized]
    336 |         result |= mask & ((uint16_t *)&tmp)[i];
	|                          ~~~~~~~~~~~~~~~~~~^~~
  /usr/src/RPM/BUILD/liboqs-0.7.1/src/kem/hqc/pqclean_hqc-rmrs-192_avx2/reed_muller.c: In function 'PQCLEAN_HQCRMRS192_AVX2_reed_muller_decode':
  /usr/src/RPM/BUILD/liboqs-0.7.1/src/kem/hqc/pqclean_hqc-rmrs-192_avx2/reed_muller.c:234:13: note: 'tmp' was declared here
    234 |     __m256i tmp = _mm256_setzero_si256();
	|             ^~~

If LTO is enabled this error message is not shown, but HQC-128 decaps
test is failed.

Link: https://github.com/open-quantum-safe/liboqs/issues/1244
Signed-off-by: Vitaly Chikunov <vt@altlinux.org>